[package]
name = "pdsmigration-common"
version = "0.1.0"
edition = "2021"
include = [
    "**/*.rs",
    "Cargo.toml",
]
license = "MIT"
publish = true
repository = "https://github.com/NorthskySocial/pds-migration"
description = "Common framework for PDS Migration"

[lib]
doctest = false

[dependencies]
serde = { workspace = true }
bsky-sdk = { workspace = true }
ipld-core = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["query", "stream"] }
derive_more = { workspace = true, features = ["display", "error"] }
futures-core = "0.3.34"
bytes = "1.12.1"
futures-util = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
base64ct = { version = "1.8.3", features = ["alloc"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "io-util", "sync"] }
wiremock = { workspace = true }
